apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-demo.fullname" . }}
  labels:
    {{- include "blog-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      # nodePort: 31000
      protocol: TCP
      name: http
  selector:
    {{- include "blog-demo.selectorLabels" . | nindent 4 }}
